---
title: "Part 9 - Logistic Regression - Social Network Ads - R"
output:
  html_document:
    df_print: paged
---



```{r}
setwd(dir = 'C:/Users/JFP1141/Downloads')
```

```{r}
dataset = read.csv('Social_Network_Ads.csv', sep = ',', header = TRUE)
head(dataset)
```

```{r}
dataset = dataset[, 3:5]
head(dataset)
```

```{r}

library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

```

```{r}
#Feature Scaling
training_set[, 1:2] = scale(training_set[, 1:2])
test_set[, 1:2] = scale(test_set[, 1:2])
```

```{r}
#Fitting Logistic Regression to the Training Set
classifier = glm(formula = Purchased ~ ., family = binomial, data = training_set )
classifier
```

```{r}
#Predicting the Test set results
prob_pred = predict(classifier, type = 'response', newdata = test_set[-3])
print(prob_pred)
```

```{r}
y_pred = ifelse(prob_pred > 0.5, 1, 0)

#Making  the Confusion matrix
cm = table(test_set[,3], y_pred)
cm
```
```{r}
# Visualising the Training set results
library(ElemStatLearn)
set = training_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
prob_set = predict(classifier, type = 'response', newdata = grid_set)
y_grid = ifelse(prob_set >0.5, 1, 0)
plot(set[, -3],
     main = 'Classifier (Training set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'pink', 'skyblue'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'red', 'blue'))
```
```{r}
# Visualising the Test set results
library(ElemStatLearn)
set = test_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
prob_set = predict(classifier, type = 'response', newdata = grid_set)
y_grid = ifelse(prob_set >0.5, 1, 0)
plot(set[, -3], main = 'Classifier (Test set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'pink', 'skyblue'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'red', 'blue'))

```